name: Deploy Latrust to Prod environement

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest


        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: copy filles to latrust server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            source: "."
            target: "/home/deploy/app/latrust_front"

        - name: Deploy application
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
                cd /home/deploy/app/latrust_front
                docker stop PRO_LATRUST_FRONTEND || true
                docker rm PRO_LATRUST_FRONTEND || true
                docker rmi latrusft_front:V1 || true
                docker build -t latrusft_front:V1 .
                docker run -d -p 8005:3000 --name PRO_LATRUST_FRONTEND latrusft_front:V1